### PR TITLE
added password change functionality

### PR DESCRIPTION
**Pull request by rafiqulshopon**

### CODE REVIEW

**Comment by rafiqulshopon** [comment]
PR for this issue - https://github.com/rafiqulshopon/graphql-apollo-mongodb/issues/3#:~:text=Ensure%20password%20changes%20are%20verified%20with%20the%20current%20password.

**Comment by rafiqulshopon** [comment]
PR for 

Update User Profile API - ( Ensure password changes are verified with the current password. )

**Review by 19sajib — COMMENTED** [review]
Should match userId from Authorization Token with User ID from payload, to make sure user updating own password,
this could be new pull request, this pull request looks good.

**Comment by rafiqulshopon** [comment]
@19sajib I am planning to implement this in the upcoming days. Thank you for your suggestion.

**Comment by rafiqulshopon** [comment]
@19sajib it would be great if you review this PR for updateUser API - 

https://github.com/rafiqulshopon/graphql-apollo-mongodb/pull/48

**Comment by 19sajib** [comment]
@rafiqulshopon  sure

**Pull request merged**
